namespace ReillyDigital.Terminal.Gui.Xaml.Generation.ProvidedClasses
{
	/// <summary>
	/// Class for source generation of the ITerminalXamlView provided class.
	/// </summary>
	public sealed class ITerminalXamlViewProvidedClass : ProvidedClassBase
	{
		/// <inheritdoc />
		public override string Name { get; } = "Terminal.Gui.Xaml.ITerminalXamlView.g.cs";

		/// <inheritdoc />
		public override string Source { get; } = @"// <auto-generated />

#nullable enable

using Terminal.Gui;

namespace Terminal.Gui.Xaml;

public interface ITerminalXamlView
{
	public void Add(View view);

	public void InitializeComponent();
}
";
	}
}
